export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_GET_PERMISSIONS = 'AUTH_GET_PERMISSIONS';

export enum TypeKeys{
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_CHECK = 'AUTH_CHECK',
  AUTH_ERROR = 'AUTH_ERROR',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_GET_PERMISSIONS = 'AUTH_GET_PERMISSIONS'
}